language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=1.2.0
    - PHP72=7.2.2
    - PHP71=7.1.14
    - PHP70=7.0.27
    - PHP56=5.6.33
    - PHP53=5.3.29
    - LATEST_TAG="${PHP72}"
  matrix:
    - PHP_VER="${PHP72}" ALPINE_VER=3.6 TAG="${PHP_VER}" EXTRA_TAG=7
    - PHP_VER="${PHP71}" ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER="${PHP70}" ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER="${PHP56}" ALPINE_VER=3.6 TAG="${PHP_VER}" EXTRA_TAG=5
    - PHP_VER="${PHP53}" ALPINE_VER=3.4 TAG="${PHP_VER}"
    - PHP_VER="${PHP72}" ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1 EXTRA_TAG=7-debug
    - PHP_VER="${PHP71}" ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER="${PHP70}" ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER="${PHP56}" ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1 EXTRA_TAG=5-debug
    - PHP_VER="${PHP53}" ALPINE_VER=3.4 TAG="${PHP_VER}-debug" PHP_DEBUG=1

script:
  - cd "${PHP_VER:0:3}/alpine${ALPINE_VER}/fpm"
#  - travis_retry make

after_success:
  - ls -la
  - ./travis-release.sh

notifications:
  on_failure: never
  slack:
    secure: |
      MUw4ma18EuITcB0cUOXVADGvcNj86G9ZqZddY5OzC9R9qea3N/+jugKudRx7oYIo708rjjjzQnT3678Z5e98zlRhYYDJUB7aUhxpOW/qdiHDra7k5p/85SgFbzjclnDT2IGaEa1MFEK/UCH2ZxoRcCNACJPOmn2FTa6YoM3foyuddplYyvfnp0IzZc1/Qbq24MAVgyPuqhHhQMcR6c6QFvPij4JChPKI355bDwUWDyraFcrzCgOskDTSoaRuyTCgB65um+SaLeo8eK71bhsQ3WremVgyiLoqtzid69Haxs5c90+1gztdGFxaBb+gMsG0Socr8zfym4+pdrwYoDYUf2Kl/WIkahxaYWX2F2igOB8bbVxVM9HE8Y87phg7p+TprgJS2BtJZ1NryVr24kF+p/SKhwT9TW3pB+bTsYJG/RFoLI5UkObahvcjFo/S6LNmsgNnzNsW6KuuV9BAlRfaETyHZglKuxhyEtJYqOC76Ka2G+0AVQ8A9UDBeLmUMXZwrn473UlQmDrl8q5C8q1wFmxeYBnXe7dj4yKygFS4k3ZCpUUsPX7VGkYv+KoVZVVZu+cNsEFBuRvyqRVAEH6BY5iIXB5Ur8/jPAhuIAI/itHy3Wz9zlIqoXQLS6kNxCXeBy616tn+wkfcoRdk93FKZzaNdeCne1ie8y16RpdwpQs=
