language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=2.0.0
    - LATEST_TAG="${PHP72}"
  matrix:
    - VARIANT=7.2/alpine3.7/fpm EXTRA_TAG=7
    - VARIANT=7.1/alpine3.7/fpm
    - VARIANT=7.0/alpine3.7/fpm
    - VARIANT=5.6/alpine3.7/fpm EXTRA_TAG=5
    - VARIANT=5.3/alpine3.4/fpm
    - VARIANT=7.2/alpine3.7/fpm PHP_DEBUG=1 EXTRA_TAG=7-debug
    - VARIANT=7.1/alpine3.7/fpm PHP_DEBUG=1
    - VARIANT=7.0/alpine3.7/fpm PHP_DEBUG=1
    - VARIANT=5.6/alpine3.7/fpm PHP_DEBUG=1 EXTRA_TAG=5-debug

script:
  - cd "${VARIANT}"
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
