language: bash
services: docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=2.1.1
    - PHP72=7.2.13
    - PHP71=7.1.25
    - PHP56=5.6.39
  matrix:
    - PHP_VER="${PHP72}" ALPINE_VER=3.8 TAGS="${PHP_VER},7.2,7,latest"
    - PHP_VER="${PHP71}" ALPINE_VER=3.8 TAGS="${PHP_VER},7.1"
    - PHP_VER="${PHP56}" ALPINE_VER=3.8 TAGS="${PHP_VER},5.6,5"
    - PHP_VER="${PHP72}" ALPINE_VER=3.8 PHP_DEBUG=1 TAGS="${PHP_VER}-debug,7.2-debug,7-debug"
    - PHP_VER="${PHP71}" ALPINE_VER=3.8 PHP_DEBUG=1 TAGS="${PHP_VER}-debug,7.1-debug"
    - PHP_VER="${PHP56}" ALPINE_VER=3.8 PHP_DEBUG=1 TAGS="${PHP_VER}-debug,5.6-debug,5-debug"

script:
  - cd "${PHP_VER:0:3}/alpine${ALPINE_VER}/fpm"
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
