language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=1.2.0
    - PHP72=7.2.3
    - PHP71=7.1.15
    - PHP70=7.0.28
    - PHP56=5.6.34
    - PHP53=5.3.29
    - LATEST_TAG="${PHP72}"
  matrix:
    - PHP_VER="${PHP72}" ALPINE_VER=3.7 TAG="${PHP_VER}" EXTRA_TAG=7
    - PHP_VER="${PHP71}" ALPINE_VER=3.7 TAG="${PHP_VER}"
    - PHP_VER="${PHP70}" ALPINE_VER=3.7 TAG="${PHP_VER}"
    - PHP_VER="${PHP56}" ALPINE_VER=3.7 TAG="${PHP_VER}" EXTRA_TAG=5
    - PHP_VER="${PHP53}" ALPINE_VER=3.4 TAG="${PHP_VER}"
    - PHP_VER="${PHP72}" ALPINE_VER=3.7 TAG="${PHP_VER}-debug" PHP_DEBUG=1 EXTRA_TAG=7-debug
    - PHP_VER="${PHP71}" ALPINE_VER=3.7 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER="${PHP70}" ALPINE_VER=3.7 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER="${PHP56}" ALPINE_VER=3.7 TAG="${PHP_VER}-debug" PHP_DEBUG=1 EXTRA_TAG=5-debug

script:
  - cd "${PHP_VER:0:3}/alpine${ALPINE_VER}/fpm"
  - travis_retry make

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis-release.sh"
