language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=7.2.2
    - BASE_IMAGE_STABILITY_TAG=1.2.0
  matrix:
    - PHP_VER=7.2.2  ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER=7.1.14 ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER=7.0.27 ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER=5.6.33 ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER=5.3.29 ALPINE_VER=3.6 TAG="${PHP_VER}"
    - PHP_VER=7.2.2  ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER=7.1.14 ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER=7.0.27 ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER=5.6.33 ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1
    - PHP_VER=5.3.29 ALPINE_VER=3.6 TAG="${PHP_VER}-debug" PHP_DEBUG=1

script:
  - cd "${PHP_VER:0:3}/alpine${ALPINE_VER}/fpm"
  - travis_retry make

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    make release

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi

notifications:
  on_failure: never
  slack:
    secure: |
      MUw4ma18EuITcB0cUOXVADGvcNj86G9ZqZddY5OzC9R9qea3N/+jugKudRx7oYIo708rjjjzQnT3678Z5e98zlRhYYDJUB7aUhxpOW/qdiHDra7k5p/85SgFbzjclnDT2IGaEa1MFEK/UCH2ZxoRcCNACJPOmn2FTa6YoM3foyuddplYyvfnp0IzZc1/Qbq24MAVgyPuqhHhQMcR6c6QFvPij4JChPKI355bDwUWDyraFcrzCgOskDTSoaRuyTCgB65um+SaLeo8eK71bhsQ3WremVgyiLoqtzid69Haxs5c90+1gztdGFxaBb+gMsG0Socr8zfym4+pdrwYoDYUf2Kl/WIkahxaYWX2F2igOB8bbVxVM9HE8Y87phg7p+TprgJS2BtJZ1NryVr24kF+p/SKhwT9TW3pB+bTsYJG/RFoLI5UkObahvcjFo/S6LNmsgNnzNsW6KuuV9BAlRfaETyHZglKuxhyEtJYqOC76Ka2G+0AVQ8A9UDBeLmUMXZwrn473UlQmDrl8q5C8q1wFmxeYBnXe7dj4yKygFS4k3ZCpUUsPX7VGkYv+KoVZVVZu+cNsEFBuRvyqRVAEH6BY5iIXB5Ur8/jPAhuIAI/itHy3Wz9zlIqoXQLS6kNxCXeBy616tn+wkfcoRdk93FKZzaNdeCne1ie8y16RpdwpQs=
