name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_IMAGE_STABILITY_TAG: 2.10.6

jobs:
  php-81:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1.4'
        tags: 8.1.4,8.1,8,latest
        workdir: 8.1/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
  php-80:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0.17'
        tags: 8.0.17,8.0
        workdir: 8.0/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
  php-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.4.28'
        tags: 7.4.28,7.4,7
        workdir: 7.4/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
