name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_IMAGE_STABILITY_TAG: 2.10.6
  PHP81: '8.1.4'
  PHP80: '8.0.17'
  PHP74: '7.4.29'

jobs:
  php-81-alpine315:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP81 }}
        tags: ${{ env.PHP81 }}-alpine3.15,8.1-alpine3.15,8-alpine3.15,${{ env.PHP81 }},8.1,8,alpine3.15,latest
        workdir: 8.1/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  php-80-alpine315:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP80 }}
        tags: ${{ env.PHP80 }}-alpine3.15,8.0-alpine3.15,8-alpine3.15,${{ env.PHP80 }},8.0
        workdir: 8.0/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  php-74-alpine315:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP74 }}
        tags: ${{ env.PHP74 }}-alpine3.15,7.4-alpine3.15,7-alpine3.15,${{ env.PHP74 }},7.4,7
        workdir: 7.4/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  php-81-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP81 }}
        tags: ${{ env.PHP81 }}-alpine3.13,8.1-alpine3.13,8-alpine3.13,alpine3.13
        workdir: 8.1/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
  php-80-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP80 }}
        tags: ${{ env.PHP80 }}-alpine3.13,8.0-alpine3.13
        workdir: 8.0/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
  php-74-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP74 }}
        tags: ${{ env.PHP74 }}-alpine3.13,7.4-alpine3.13,7-alpine3.13
        workdir: 7.4/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
